[versions]
androidGradlePlugin = "8.0.0-alpha06"
kotlin_version = "1.7.20"


[libraries]


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }